// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Tests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("History")]
    public partial class HistoryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "History.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests", "History", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clear history")]
        public virtual void ClearHistory()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Clear history", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given("I login as \'Jack\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Interest",
                            "Income"});
                table1.AddRow(new string[] {
                            "1000",
                            "10",
                            "100",
                            "50",
                            "1050"});
                table1.AddRow(new string[] {
                            "1000",
                            "20",
                            "50",
                            "100",
                            "1100"});
#line 5
  testRunner.And("I have history data:", ((string)(null)), table1, "And ");
#line hidden
#line 9
 testRunner.When("I open History page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
  testRunner.And("I clear the history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Year",
                            "From",
                            "To",
                            "Interest",
                            "Income"});
#line 11
 testRunner.Then("the History is:", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("History table")]
        public virtual void HistoryTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("History table", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 15
 testRunner.Given("I login as \'Jack\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Fin Year",
                            "Start Date",
                            "Interest",
                            "Income"});
                table3.AddRow(new string[] {
                            "1000",
                            "10",
                            "100",
                            "360",
                            "10/01/2022",
                            "50",
                            "1050"});
                table3.AddRow(new string[] {
                            "1000",
                            "20",
                            "50",
                            "365",
                            "15/05/2022",
                            "100",
                            "1100"});
#line 16
  testRunner.And("I have history data:", ((string)(null)), table3, "And ");
#line hidden
#line 20
 testRunner.When("I open History page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Year",
                            "From",
                            "To",
                            "Interest",
                            "Income"});
                table4.AddRow(new string[] {
                            "1,000.00",
                            "20%",
                            "50",
                            "365",
                            "15/05/2022",
                            "04/07/2022",
                            "100.00",
                            "1,100.00"});
                table4.AddRow(new string[] {
                            "1,000.00",
                            "10%",
                            "100",
                            "360",
                            "10/01/2022",
                            "20/04/2022",
                            "50.00",
                            "1,050.00"});
#line 21
 testRunner.Then("the History is:", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("History shows last 9 rows")]
        public virtual void HistoryShowsLast9Rows()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("History shows last 9 rows", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 27
 testRunner.Given("I login as \'Jack\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Fin Year",
                            "Start Date",
                            "Income",
                            "Interest"});
                table5.AddRow(new string[] {
                            "1001",
                            "1",
                            "101",
                            "360",
                            "01/01/2022",
                            "10010",
                            "10"});
                table5.AddRow(new string[] {
                            "1002",
                            "2",
                            "102",
                            "365",
                            "02/05/2022",
                            "10020",
                            "20"});
                table5.AddRow(new string[] {
                            "1003",
                            "3",
                            "103",
                            "360",
                            "03/01/2022",
                            "10030",
                            "30"});
                table5.AddRow(new string[] {
                            "1004",
                            "4",
                            "104",
                            "365",
                            "04/05/2022",
                            "10040",
                            "40"});
                table5.AddRow(new string[] {
                            "1005",
                            "5",
                            "105",
                            "360",
                            "05/01/2022",
                            "10050",
                            "50"});
                table5.AddRow(new string[] {
                            "1006",
                            "6",
                            "106",
                            "365",
                            "06/05/2022",
                            "10060",
                            "60"});
                table5.AddRow(new string[] {
                            "1007",
                            "7",
                            "107",
                            "360",
                            "07/01/2022",
                            "10070",
                            "70"});
                table5.AddRow(new string[] {
                            "1008",
                            "8",
                            "108",
                            "365",
                            "08/05/2022",
                            "10080",
                            "80"});
                table5.AddRow(new string[] {
                            "1009",
                            "9",
                            "109",
                            "360",
                            "09/01/2022",
                            "10090",
                            "90"});
                table5.AddRow(new string[] {
                            "1010",
                            "10",
                            "110",
                            "365",
                            "10/05/2022",
                            "10100",
                            "100"});
                table5.AddRow(new string[] {
                            "1011",
                            "11",
                            "111",
                            "360",
                            "11/01/2022",
                            "10110",
                            "110"});
                table5.AddRow(new string[] {
                            "1012",
                            "12",
                            "112",
                            "365",
                            "12/05/2022",
                            "10120",
                            "120"});
#line 28
  testRunner.And("I have history data:", ((string)(null)), table5, "And ");
#line hidden
#line 42
 testRunner.When("I open History page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Year",
                            "From",
                            "To",
                            "Interest",
                            "Income"});
                table6.AddRow(new string[] {
                            "1,012.00",
                            "12%",
                            "112",
                            "365",
                            "12/05/2022",
                            "01/09/2022",
                            "120.00",
                            "10,120.00"});
                table6.AddRow(new string[] {
                            "1,011.00",
                            "11%",
                            "111",
                            "360",
                            "11/01/2022",
                            "02/05/2022",
                            "110.00",
                            "10,110.00"});
                table6.AddRow(new string[] {
                            "1,010.00",
                            "10%",
                            "110",
                            "365",
                            "10/05/2022",
                            "28/08/2022",
                            "100.00",
                            "10,100.00"});
                table6.AddRow(new string[] {
                            "1,009.00",
                            "9%",
                            "109",
                            "360",
                            "09/01/2022",
                            "28/04/2022",
                            "90.00",
                            "10,090.00"});
                table6.AddRow(new string[] {
                            "1,008.00",
                            "8%",
                            "108",
                            "365",
                            "08/05/2022",
                            "24/08/2022",
                            "80.00",
                            "10,080.00"});
                table6.AddRow(new string[] {
                            "1,007.00",
                            "7%",
                            "107",
                            "360",
                            "07/01/2022",
                            "24/04/2022",
                            "70.00",
                            "10,070.00"});
                table6.AddRow(new string[] {
                            "1,006.00",
                            "6%",
                            "106",
                            "365",
                            "06/05/2022",
                            "20/08/2022",
                            "60.00",
                            "10,060.00"});
                table6.AddRow(new string[] {
                            "1,005.00",
                            "5%",
                            "105",
                            "360",
                            "05/01/2022",
                            "20/04/2022",
                            "50.00",
                            "10,050.00"});
                table6.AddRow(new string[] {
                            "1,004.00",
                            "4%",
                            "104",
                            "365",
                            "04/05/2022",
                            "16/08/2022",
                            "40.00",
                            "10,040.00"});
#line 43
 testRunner.Then("the History is:", ((string)(null)), table6, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("History respect settings")]
        [NUnit.Framework.TestCaseAttribute("$ - US dollar", "123.456.789,00", "dd-MM-yyyy", "11-10-2022", "06-08-2023", "100.000,00", "81.098,63", "181.098,63", null)]
        [NUnit.Framework.TestCaseAttribute("€ - euro", "123 456 789.00", "MM/dd/yyyy", "10/11/2022", "08/06/2023", "100 000.00", "81 098.63", "181 098.63", null)]
        [NUnit.Framework.TestCaseAttribute("£ - Great Britain Pound", "123 456 789,00", "MM dd yyyy", "10 11 2022", "08 06 2023", "100 000,00", "81 098,63", "181 098,63", null)]
        public virtual void HistoryRespectSettings(string currency, string numberFormat, string dateFormat, string from, string to, string amount, string interest, string income, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("currency", currency);
            argumentsOfScenario.Add("number format", numberFormat);
            argumentsOfScenario.Add("date format", dateFormat);
            argumentsOfScenario.Add("from", from);
            argumentsOfScenario.Add("to", to);
            argumentsOfScenario.Add("amount", amount);
            argumentsOfScenario.Add("interest", interest);
            argumentsOfScenario.Add("income", income);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("History respect settings", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
 testRunner.Given("I login as \'Jack\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
  testRunner.And(string.Format("I update settings: \'{0}\', \'{1}\', \'{2}\'", numberFormat, dateFormat, currency), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
  testRunner.And("I open Calculator page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
  testRunner.And("I select Start Date as \'10/11/2022\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
  testRunner.And("I calculate deposit for $100000 with 99% on 299 days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 61
 testRunner.When("I open History page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Amount",
                            "%",
                            "Term",
                            "Year",
                            "From",
                            "To",
                            "Interest",
                            "Income"});
                table7.AddRow(new string[] {
                            string.Format("{0}", amount),
                            "99%",
                            "299",
                            "365",
                            string.Format("{0}", from),
                            string.Format("{0}", to),
                            string.Format("{0}", interest),
                            string.Format("{0}", income)});
#line 62
 testRunner.Then("the History is:", ((string)(null)), table7, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
